# Generated by Django 4.2.2 on 2023-07-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='HProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Hompage Project',
                'verbose_name_plural': 'Hompage Projects',
            },
        ),
    ]
